SELECT C.CAR_ID CAR_ID, C.CAR_TYPE CAR_TYPE, FLOOR(DAILY_FEE * 30 * (100 - DISCOUNT_RATE) / 100) AS FEE FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON C.CAR_TYPE = P.CAR_TYPE
    AND DURATION_TYPE = '30일 이상'
WHERE (C.CAR_TYPE = 'SUV' OR C.CAR_TYPE = '세단')
    AND C.CAR_ID NOT IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE NOT (START_DATE > '2022-11-30' OR END_DATE < '2022-11-01'))
    AND DAILY_FEE * 30 * (100 - DISCOUNT_RATE) / 100 >= 500000
    AND DAILY_FEE * 30 * (100 - DISCOUNT_RATE) / 100 < 2000000
ORDER BY CAR_ID;
