-- SELECT ID, EMAIL, FIRST_NAME, LAST_NAME FROM DEVELOPERS WHERE SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') > 0 OR SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'PYTHON') > 0 ORDER BY 1;

SELECT DISTINCT ID, EMAIL, FIRST_NAME, LAST_NAME FROM DEVELOPERS JOIN SKILLCODES ON DEVELOPERS.SKILL_CODE & SKILLCODES.CODE > 0 WHERE NAME = 'C#' OR NAME = 'PYTHON' ORDER BY 1;